# Generated by Django 5.1.3 on 2024-12-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
